# 1. Functions/Input

In [ ]:
# take user input
input_1 = input("String 1 here: ") 

input_2 = input("String 2 here: ")
# define the function
def contains(s1, s2):
    if s2 in s1:
        return True
    return False

    return # some boolean

print(contains(input_1, input_2))

# 2. NumPy/Pandas

In [20]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "A": np.linspace(1,10,10),
    "B": np.linspace(10,1,10),
    "C": 7*np.ones(10),
    "D": np.random.randint(1,11,size=10),
    "E": np.random.randint(1,11,size=10),
    "F": np.random.randint(1,11,size=10)
})
print(df)
# numpy
arr = np.random.randn(2, 4)
print(arr)
arr = arr.T
print(arr)
print(arr[1:3, :, np.newaxis])
print(arr[:, 0])
print(arr[..., 0])

      A     B    C   D  E  F
0   1.0  10.0  7.0   9  8  7
1   2.0   9.0  7.0   3  8  9
2   3.0   8.0  7.0   4  1  5
3   4.0   7.0  7.0   1  6  5
4   5.0   6.0  7.0   7  1  1
5   6.0   5.0  7.0  10  9  5
6   7.0   4.0  7.0   5  7  2
7   8.0   3.0  7.0   3  1  9
8   9.0   2.0  7.0  10  9  3
9  10.0   1.0  7.0   4  3  8
[[-0.45473247 -0.41457742 -0.36984347  0.53744499]
 [-1.9124696  -0.17332396  1.30797093 -1.11961264]]
[[-0.45473247 -1.9124696 ]
 [-0.41457742 -0.17332396]
 [-0.36984347  1.30797093]
 [ 0.53744499 -1.11961264]]
[[[-0.41457742]
  [-0.17332396]]

 [[-0.36984347]
  [ 1.30797093]]]
[-0.45473247 -0.41457742 -0.36984347  0.53744499]
[-0.45473247 -0.41457742 -0.36984347  0.53744499]


# 3. OOP

In [8]:

class Lipsum:
    def __init__(self):
      f = open("lipsum.txt")
      self.data = f.read()
      f.close()
    def word_count(self):
        return [(x, len(x.split(" "))) for x in self.data.split(". ")]
    def first_position(self, tups):
        return [ { c : x[0].count(c) for c in set(x[0].translate({ord(","): None, ord(" "): None})) } for x in tups]


thing = Lipsum()
print(thing.word_count())
print(thing.first_position(thing.word_count()))

[('Lorem ipsum dolor sit amet, consectetur adipiscing elit', 8), ('Vestibulum non diam nulla', 4), ('Vivamus ac mi tempus, iaculis lacus sit amet, aliquet tellus', 10), ('Praesent eleifend laoreet sem non sagittis', 6), ('Pellentesque egestas odio sit amet gravida fermentum', 7), ('Mauris facilisis et lorem non luctus', 6), ('Donec consectetur rhoncus diam', 4), ('Donec gravida enim quis vulputate tincidunt', 6), ('Suspendisse mauris orci, efficitur nec euismod ut, porttitor a velit', 10), ('Fusce et sapien quis metus blandit malesuada non eget nisi', 10), ('Nunc est felis, malesuada at odio sit amet, ultrices molestie sem', 11), ('Curabitur porttitor quam porttitor libero vulputate blandit', 7), ('Nulla maximus interdum lobortis', 4), ('Maecenas et felis fermentum, mollis odio congue, efficitur lorem', 9), ('In vel tellus ultrices, feugiat ex quis, elementum felis', 9), ('Aliquam volutpat hendrerit orci, eget euismod massa tempus sit amet', 10), ('Mauris urna tellus, accumsan non aliq